language: en
pipeline:
- name: "rasa.thai_tokenize.thai_tokenize"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
  "token_pattern": .*
- name: "intent_classifier_tensorflow_embedding"